### Pytorch 에서의 Gradient Descent
    우리는 이전 머신러닝 과정에서 선형회귀(Linear Regression)에 대해서 간단히 살펴보았다.
    이번에는 파이토치를 이용해서 선형회귀를 위한 연산 그래프를 만들고 경사하강법을 이해하는 코드
    를 다시 작성해 보자. 파이토치에서는 데이터의 기본단위로 텐서(Tensor)를 사용한다.
    Numpy에서 np.array([1,2,3]) 과 동일한 것.
    이러한 텐서를 연산의 기본 단위로 사용한다. 텐서를 생성하는 방법에는 torch.tensor() ...

In [1]:
import torch # pytorch는 그냥 torch로 불러온다
import torchvision # 파이토치에서 vision은 Image Processing에 특화된 라이브러리
import torch.nn as nn # nn은 Neural Net의 약자
import numpy as np
import torchvision.transforms as transforms # transforms... data augmentation

In [2]:
X = torch.Tensor(2,3) #2행 3열로 텐서를 만든다. 값은 랜덤하게 들어감.
X

tensor([[9.2755e-39, 6.3368e-39, 9.2755e-39],
        [9.2755e-39, 1.0653e-38, 1.0469e-38]])

In [3]:
X.shape

torch.Size([2, 3])

In [4]:
X.size()

torch.Size([2, 3])

In [5]:
X = torch.Tensor([[1,2,3],[4,5,6]])
X

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [6]:
'''
tensor() 함수의 인자값으로 data.dtype, device, requires_grad 등이 있다.
dtype - 데이터 값의 타입 지정
device - 텐서를 어느 기기에 올릴 것인가를 지정...(CPU, GPU)
requires_grad - 텐서의 기울기를 지정할지를 여부..(기본값은 False)... 미분 사용 여부 
                => 이거 안 넣어주면 미분 못하고 Back Propagation 안 써서 학습이 안 됨
                => Traing Model은 학습을 해야 하기 때문에 반드시 True로 설정해야 함.
                => Test Model은 학습을 안 하므로 False로 해놓음. True로 해도 상관은 없는데 굳이 할 필요 없고 자원만 씀.
'''
x = torch.tensor(data=[2.0, 3.0], requires_grad=True)
x

tensor([2., 3.], requires_grad=True)

In [7]:
y = x**2
y

tensor([4., 9.], grad_fn=<PowBackward0>)

In [8]:
# 1. 예측값 출력
pred = 2*y + 3 # 2X^2 + 3
pred

tensor([11., 21.], grad_fn=<AddBackward0>)

In [9]:
target = torch.tensor([3.0, 4.0]) #라벨(정답)
target

tensor([3., 4.])

In [10]:
# 2. loss 값을 구한다
loss = torch.sum(torch.abs(pred-target)) # (11-3) + (21-4) = 25
loss
print('loss ', loss)

loss  tensor(25., grad_fn=<SumBackward0>)


In [11]:
# 3.가장 가파른 기울기로 하강하는 Weight를 찾는다.
# = 가장 낮은 loss값을 구하는 Weight를 찾는다..... 미분, 편미분... Back Propagation
loss.backward()

'''
x.grad ---> dy/dw = x (미분공식)
w.grad ---> dy/dx = w
'''
print(x.grad, pred.grad)

tensor([ 8., 12.]) None


### Tensor Type - tensor(), as_tensor()
    Numpy 배열을 torch.Tensor 타입으로 변형

In [20]:
'''
Pytorch의 텐서 자료형은 Numpy의 array()와 동일한 것으로 이해...

'''
# 1. Numpy 배열을 torch.Tensor 타입으로 변형
li = np.array([[1,2],[3,4]])
print(li)
print(li.dtype)
print(type(li))

print('*'*40)

li_torch = torch.tensor(li)
print(li_torch)
print(type(li_torch))

print('*'*40)

li_as_torch = torch.as_tensor(li)
print(li_as_torch)
print(type(li_as_torch))

[[1 2]
 [3 4]]
int32
<class 'numpy.ndarray'>
****************************************
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
<class 'torch.Tensor'>
****************************************
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
<class 'torch.Tensor'>


In [23]:
# 2. 반대로 텐서를 Numpy 배열로 변형... torch.numpy()를 사용한다.
li_tensor_numpy = li_as_torch.numpy()
print(li_tensor_numpy)
print(type(li_tensor_numpy))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
