In [4]:
import keras
from keras import models, layers
import numpy as np

In [2]:
# 1. Data Generator
x = np.array([0,1,2,3,4])
y = 2 * x + 1

print(x)
print(y)

[0 1 2 3 4]
[1 3 5 7 9]


In [8]:
# 2. Model Generator
'''
units - 히든레이어의 유닛의 개수
**kwargs : 이런 건 없다... input_shape=(1,)
'''
model=models.Sequential() #x값이 입력되고 Hidden Layer를 거쳐서 y값으로 출력
# Fully Connected Layer를 만들 때 Dense(빽빽한, 밀집함)
model.add(layers.Dense(1,input_shape=(1,))) #레이어에 들어있는 유닛의 개수, **kwargs에 포함되는 게 input_shape
# layers.Dense?

In [9]:
# 3. ... optimizer에 해당하는 부분, loss에 해당하는 부분... complie
model.compile(optimizer=keras.optimizers.sgd(0.01), loss='mse', metrics=['accuracy']) #0.01은 learning rate

In [13]:
# 4. 학습을 진행
model.fit(x[:4], y[:4], epochs=100, verbose=0) 
#원래는 하이퍼파라미터 변수로 뽑아내는 게 더 좋음
# verbose를 1이나 2로 주면 tracing을 하면서 메모리를 많이 잡아먹고 속도 느림. 
print(x[:4])
print(y[:4])

[0 1 2 3]
[1 3 5 7]


In [16]:
# 5. 예측
print('Y Value : ', y[3:])
print('Prediction : ', model.predict(x[3:]))
print('Prediction : ', model.predict(x[3:]).flatten()) #1차원으로 펼침

Y Value :  [7 9]
Prediction :  [[6.9515004]
 [8.89543  ]]
Prediction :  [6.9515004 8.89543  ]


In [21]:
# 6. Evaluate
eval_model = model.evaluate(x[3:], y[3:], verbose=0)
print('Loss {}, Accuracy : {}'.format(*eval_model)) 
# * => 파이썬에서 굉장히 많이 씀. 가변변수 안에서 요소가 몇개 있는지 모르지만 하나씩 불러오려고 할 때 쓴다.
# 파이썬에서 많이 써서 파이썬 라이브러리에서도 많이 씀.

Loss 0.006643588189035654, Accuracy : 1.0
