#### 인덱싱, 슬라이싱

In [9]:
import numpy as np

In [10]:
# 중요한 개념은 판다스에서 나옴(loc, iloc, at, iat)

narray = np.arange(5)
print(narray)
print(narray[1], narray[-1]) # 음수가 붙으면 뒤에서 n번째로 이해
print(narray[1:])
print(narray[1:5])
print(narray[:]) # 전부 다 출력
print(narray[2:4]) # 두번째 인덱스는 포함하지 않는다.

[0 1 2 3 4]
1 4
[1 2 3 4]
[1 2 3 4]
[0 1 2 3 4]
[2 3]


In [11]:
'''
2차원 배열에서의 인덱싱, 슬라이싱
인덱스는 [ , ] 콤마를 기준으로 2개의 인자를 받는다.
앞의 인자값은 행의 index, 뒤 인자값은 열의 index

, 없이 : 를 넣으면 모든 것을 다 포함한다.
'''

'\n2차원 배열에서의 인덱싱, 슬라이싱\n인덱스는 [ , ] 콤마를 기준으로 2개의 인자를 받는다.\n앞의 인자값은 행의 index, 뒤 인자값은 열의 index\n\n, 없이 : 를 넣으면 모든 것을 다 포함한다.\n'

In [12]:
np.random.seed(100) # 고정적인 난수값(seed값) 설정
narray1 = np.random.randint(0, 20, 16).reshape(4, 4)
print(narray1)

[[ 8  3  7 15]
 [16 10  2  2]
 [ 2 14  2 17]
 [16 15  4 11]]


In [13]:
#1. narray1 에서 첫번째줄 7을 가져오려면
print(narray1[0,2])
print(narray1[0][2]) # 위와 같은 값

print('*'*30)

#2. 두번째 라인 [16 10  2  2]을 가져오려면
print(narray1[1,0:4])
print(narray1[1,0:])
print(narray1[1,:])
print(narray1[1])
print(narray1[1:2, :]) # 2차원 출력

print('*'*30)

#3, 전체 행에 대해서 4번째 열만 다 가져오려면
print(narray1[0:4, 3:4]) #1,2,3,4행 다 가져오고 마지막꺼
print(narray1[:, 3:])
print(narray1[:,3]) #차원이 줄어든다.

print('*'*30)

#4. 전체행에 대해서 1,2번째 열만 다 가져오려면
narray1[:, :2]

7
7
******************************
[16 10  2  2]
[16 10  2  2]
[16 10  2  2]
[16 10  2  2]
[[16 10  2  2]]
******************************
[[15]
 [ 2]
 [17]
 [11]]
[[15]
 [ 2]
 [17]
 [11]]
[15  2 17 11]
******************************


array([[ 8,  3],
       [16, 10],
       [ 2, 14],
       [16, 15]])

### 인덱싱과 슬라이싱

In [14]:
np.random.seed(0) 
arr3 = np.random.randn(4,4)
arr3 

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433]])

In [15]:
#1. 논리연산자 사용
print(arr3[arr3>0])
print(arr3[arr3<0])

[1.76405235 0.40015721 0.97873798 2.2408932  1.86755799 0.95008842
 0.4105985  0.14404357 1.45427351 0.76103773 0.12167502 0.44386323
 0.33367433]
[-0.97727788 -0.15135721 -0.10321885]


In [16]:
#2. 0보다 작은 값들을 전부 0으로 바꿔보겠다.
arr3[arr3<0] = 0
arr3 # 원본도 같이 바뀐다.

array([[1.76405235, 0.40015721, 0.97873798, 2.2408932 ],
       [1.86755799, 0.        , 0.95008842, 0.        ],
       [0.        , 0.4105985 , 0.14404357, 1.45427351],
       [0.76103773, 0.12167502, 0.44386323, 0.33367433]])

In [17]:
#3. where 함수
'''
arr3가 0이 아니면 arr3를 그대로 리턴
arr3가 0이면 -1을 리턴....
'''

arr3_1 = np.where(arr3!=0, arr3, -1)
arr3_1

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -1.        ,  0.95008842, -1.        ],
       [-1.        ,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433]])

In [18]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)
bool_a = (a>2) # 2보다 크면 true
print(bool_a)

print(a[bool_a]) # a의 요소로 bool_a를 집어넣으면 true인 것만 리턴됨.
print(a[a>2])

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


### Numpy 통계함수

In [19]:
arr4 = np.random.randint(0,20, 16).reshape(4,4)
arr4 #seed는 한번만 해주면 되므로 같은 난수값 나옴.

array([[18,  3, 17, 19],
       [19, 19, 14,  7],
       [ 0,  1,  9,  0],
       [10,  3, 11, 18]])

In [20]:
'''
numpy 배열의 통계함수
sum(), mean(), min(), max(), argmin(), argmax(), cumsum()
//argmin - 아규먼트 중에 최소 아규먼트 / argmax - 아규먼트 중에서 최대 아규먼트
//cumsum - 누적합 구하는 것
'''

np.sum(arr4) #168

#axis=0은 행 기준 (|, |, |, |)
#axis=1은 열 기준(ㅡ, ㅡ, ㅡ, ㅡ)
print(np.sum(arr4, axis=0)) #행 기준으로 합침
print(np.sum(arr4, axis=1)) #열 기준으로 합침
print(np.cumsum(arr4, axis=0)) #행 기준으로 누적합
'''
axis=0
모든 행들을 다 검색
그 중에서 가장 큰 값의 인덱스를 리턴하도록
'''
print(np.argmax(arr4, axis=0))

'''
[18,  3, 17, 19],
[19, 19, 14,  7],
[ 0,  1,  9,  0],
[10,  3, 11, 18]
에서 18, 19, 0, 0 중에서 19가 가장 크니까 인덱스 1
3, 19, 1, 3 중에서 19가 가장 크니까 인덱스 1
17, 14, 9, 11 중에서 17이 가장 크니까 인덱스 0
19, 7, 0, 18 중에서 19가 가장 크니까 인덱스 0
'''

[47 26 51 44]
[57 59 10 42]
[[18  3 17 19]
 [37 22 31 26]
 [37 23 40 26]
 [47 26 51 44]]
[1 1 0 0]


'\n[18,  3, 17, 19],\n[19, 19, 14,  7],\n[ 0,  1,  9,  0],\n[10,  3, 11, 18]\n에서 18, 19, 0, 0 중에서 19가 가장 크니까 인덱스 1\n3, 19, 1, 3 중에서 19가 가장 크니까 인덱스 1\n17, 14, 9, 11 중에서 17이 가장 크니까 인덱스 0\n19, 7, 0, 18 중에서 19가 가장 크니까 인덱스 0\n'